[package]
name = "rust-raycaster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Logging
log = "0.4.20"
env_logger = "0.11.2"

# Graphics
sdl2 = "0.36.0"

# ECS
ecs_rust = "0.0.4"
